export const navWrapper: string;
export const mainArea: string;
export const subArea: string;
export const outArea: string;
export const commonButton: string;
export const subButton: string;
export const selected: string;
export const navButton: string;
export const organizationButton: string;
